name: Documentation

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  docgen:
    uses: sapphiredev/.github/.github/workflows/reusable-docgen.yml@main
    with:
      project-name: pieces
    secrets:
      SKYRA_TOKEN: ${{ secrets.SKYRA_TOKEN }}
